feature: support multiple validation errors to devel branch
CESNET/libyang pull request #1341
Opened 2021-01-09 08:12 UTC by fanchanghu

Hi,
This is the same PR with #1337 to devel branch.

I also removed the option `LYD_OPT_MULTI_ERRORS` according to your request, please check it, thanks.

2021-01-12 14:35 UTC, michalvasko commented
Thanks, but the point of my request to make it all much simpler without useless arguments. Ignore whether all the errors can be stored, they will all be printed in any case. I was hoping you can simply change the `resolve_must` function and that will be it, no new parameters anywhere.

2021-01-13 01:35 UTC, fanchanghu commented
Hi,
I think it's better to use the log option, because:

1. If the log option `LY_LOSTORE_LAST` is set, the user can only get one error even if multiple errors are detected. 
2. Detecting multiple errors is inefficient when the user just wants to return from the first error. 
3. I think you may want to keep the api compatible for libyang1, Detecting multiple errors as default may breakdown some users. (return the last error instand of the first one.)

2021-01-13 08:05 UTC, michalvasko commented
Okay, we have discussed this change properly and have decided that the new option is the right solution after all, sorry about that. Also, please try to keep the code reasonably clean. For example, use 2 return values in `resolve_data_unres` instead of performing `|` on a single one. You can make these changes in this PR, even force-pushing a completely new commit is fine.

2021-01-13 12:58 UTC, michalvasko requested changes
Okay, except for minor formatting errors it seems fine.

2021-01-13 12:58 UTC, michalvasko commented on src/resolve.c
> +            if(!multi_error) {
Space after `if`.

2021-01-13 12:58 UTC, michalvasko commented on src/resolve.c
> +                if(!multi_error) {
Space after `if`.

2021-01-14 08:41 UTC, michalvasko approved these changes

2021-01-14 08:43 UTC, merged