support plugin to skip loading special extension instance.
CESNET/libyang pull request #1356
Opened 2021-01-19 11:49 UTC by fanchanghu

Hi,
This PR is for the issue #1345 , however, it is a little more complex than I expected.

Please have a look and give some suggestions, thanks.  @rkrejci 

I will still work on this to add some tests if there is no major problems in this code.

2021-01-20 10:35 UTC, rkrejci requested changes

2021-01-20 10:35 UTC, rkrejci commented on src/parser.h
> +int lyp_get_ext_list(struct ly_ctx *ctx, void *elem, LYEXT_PAR elem_type,
Please add doxygen description with the short comment about the purpose of the function and its parameters.

2021-01-20 10:35 UTC, rkrejci commented on src/parser_yang.c
> +            /* this extension is skipped, move all extensions after it */
what about using `memmove(3)`?

2021-01-20 10:35 UTC, rkrejci commented on src/parser_yin.c
> +        // extension instance is skipped
please use block comments `/* */`

2021-01-20 10:35 UTC, rkrejci commented on src/resolve.c
> +save_ignored_ext_parent(int resolve_rc, struct ly_set *ext_parents, struct ly_set *ext_par_types,
please add doxygen description comment about the function and its parameters

2021-01-20 10:35 UTC, rkrejci commented on src/resolve.c
> +compack_ext_list(struct ly_ctx *ctx, void *elem, LYEXT_PAR elem_type)
please add doxygen description comment about the function and its parameters

2021-01-20 10:35 UTC, rkrejci commented on src/resolve.c
> +    finish:
formatting - move the label to the column 0

2021-01-20 10:38 UTC, rkrejci commented
Could you please also, here or in the referenced issue, a little elaborate on why the change is more complex than we've expected? I agree that the test will be needed, but except for the minor issues I've pointed out, it seems fine to me.

2021-01-21 02:32 UTC, fanchanghu commented
Hi,
The review issues have been fixed, please have a look again, thanks.

I only thought of processing the skipped extension instance when parsing it at first, however, when I worked on this, I found that it also need be processed when resolved. And there could be more than 1 skipped extension instances when resolving, so I have to saving their parents in a set and compact the extension instance arrays later. That's why I said it was a little complex than I expected.

2021-01-21 10:19 UTC, rkrejci commented
ok, the code looks fine to me now, are you going to add some test cases?

2021-01-21 10:27 UTC, michalvasko approved these changes

2021-01-21 10:38 UTC, fanchanghu commented
Yes, I'm working on the test cases now, the test cases will be pushed later, with a memory leak issue (found by the test cases) patch.

2021-01-21 11:55 UTC, fanchanghu commented
Hi,
The test cases and memory leak issue patch have been committed, please check it, thanks.

2021-01-21 12:54 UTC, rkrejci approved these changes

2021-01-21 12:56 UTC, merged