Isa plugin refactor put error print message into function ly_err_msg_create
CESNET/libyang pull request #1456
Opened 2021-03-08 12:04 UTC by radek-isa

2021-03-08 13:15 UTC, michalvasko reviewed
Right, this was one of the features I knew was missing, so good that you have added it and it seems fine. However, please also add a test for the apptag being specified in the YANG and returned by some type validation.

2021-03-10 12:36 UTC, michalvasko approved these changes

2021-03-11 07:57 UTC, rkrejci requested changes

2021-03-11 07:57 UTC, rkrejci commented on src/plugins_types.c
> + * @param [in] path   	Path to the node causing the error.
inconsistent indentation, keep there just a single space

2021-03-11 08:58 UTC, rkrejci commented on src/plugins_types.c
> + * @param [in] path   	Path to the node causing the error.
I see that it was changed in a later commit, but I don't see any reason to do not to rebase the fix back into the commit it introduced the spaces. And even after the later change, there are still more spaces.

2021-03-11 09:24 UTC, rkrejci approved these changes

2021-03-11 09:29 UTC, merged